variables:
  GIT_STRATEGY: none
  GIT_SUBMODULE_STRATEGY: recursive
  OPENMC_CROSS_SECTIONS: $CI_PROJECT_DIR/nndc_hdf5/cross_sections.xml
  OPENMC_ENDF_DATA: $CI_PROJECT_DIR/endf-b-vii.1
  CC: mpicc
  CXX: mpicxx
  FC: mpif90
  F77: mpif77

stages:
  - build_petsc
  - build_libmesh
  - build_onepebble
  - download
  - test

build_petsc:petsc:
  stage: build_petsc
  variables:
    GIT_STRATEGY: fetch
  script: 
    - cd contrib/moose
    - scripts/update_and_rebuild_petsc.sh

build_libmesh:libmesh:
  stage: build_libmesh
  dependencies:
    - build_petsc:petsc
  script: 
    - cd contrib/moose
    - scripts/update_and_rebuild_libmesh.sh

build_onepebble:onepebble:
  stage: build_onepebble
  dependencies:
    - build_petsc:petsc
    - build_libmesh:libmesh
  script:
    - make -j4 NEK_CASENAME=onepebble NEK_CASEDIR="$CI_PROJECT_DIR/problems/spherical_heat_conduction"

download:cross_sections:
  stage: download
  script:
    - if [[ ! -e $OPENMC_CROSS_SECTIONS ]]; then wget -q -O - https://anl.box.com/shared/static/pzutl4i2717yypv12l78l7fn5nmg6grs.xz | tar -C $CI_PROJECT_DIR -xJ; fi
    - if [[ ! -d $OPENMC_ENDF_DATA/neutrons || ! -d $OPENMC_ENDF_DATA/photoat || ! -d $OPENMC_ENDF_DATA/atomic_relax ]]; then wget -q -O - https://anl.box.com/shared/static/4kd2gxnf4gtk4w1c8eua5fsua22kvgjb.xz | tar -C $CI_PROJECT_DIR -xJ; fi

test:onepebble_openmc:
  stage: test
  dependencies:
    - build_onepebble:onepebble
    - download:cross_sections
  script:
    - cd problems/spherical_heat_conduction
    - mpirun -np 2 "$CI_PROJECT_DIR/cardinal-onepebble-opt" --app openmc -i openmc.i --n-threads=8

