variables:
  GIT_STRATEGY: none
  GIT_SUBMODULE_STRATEGY: none
  OPENMC_CROSS_SECTIONS: $CI_PROJECT_DIR/nndc_hdf5/cross_sections.xml
  OPENMC_ENDF_DATA: $CI_PROJECT_DIR/endf-b-vii.1
  CC: mpicc
  CXX: mpicxx
  FC: mpif90
  F77: mpif77
  METHOD: opt
  N_RANKS: 2
  N_THREADS: 4

stages:
  - submodule_update
  - build_petsc
  - build_libmesh
  - build_cardinal
  - nrspre_onepebble2
  - download
  - test

submodule_update:submodules:
  stage: submodule_update
  variables:
    GIT_STRATEGY: clone
  script:
    - env | sort
    - git submodule update --init --recursive contrib/openmc
    - git submodule update --init contrib/nekRS
    - git submodule update --init contrib/moose

build_petsc:petsc:
  stage: build_petsc
  script: 
    - env | sort
    - cd contrib/moose
    - scripts/update_and_rebuild_petsc.sh

build_libmesh:libmesh:
  stage: build_libmesh
  script: 
    - env | sort
    - cd contrib/moose
    - scripts/update_and_rebuild_libmesh.sh  --disable-vtk

build_cardinal:cardinal:
  stage: build_cardinal
  script:
    - env | sort
    - make -j4

nrspre_onepebble2:nrspre:
  stage: nrspre_onepebble2
  variables:
    NEKRS_HOME: $CI_PROJECT_DIR/install
  script:
    - env | sort
    - cd problems/spherical_heat_conduction
    - $NEKRS_HOME/bin/nrspre onepebble2 "$N_RANKS"

download:cross_sections:
  stage: download
  script:
    - if [[ ! -e $OPENMC_CROSS_SECTIONS ]]; then wget -q -O - https://anl.box.com/shared/static/teaup95cqv8s9nn56hfn7ku8mmelr95p.xz | tar -C $CI_PROJECT_DIR -xJ; fi
    - if [[ ! -d $OPENMC_ENDF_DATA/neutrons || ! -d $OPENMC_ENDF_DATA/photoat || ! -d $OPENMC_ENDF_DATA/atomic_relax ]]; then wget -q -O - https://anl.box.com/shared/static/4kd2gxnf4gtk4w1c8eua5fsua22kvgjb.xz | tar -C $CI_PROJECT_DIR -xJ; fi

test:app_openmc:openmc.i:
  stage: test
  timeout: 30m
  script:
    - env | sort
    - cd problems/spherical_heat_conduction
    - mpirun -np "$N_RANKS" "$CI_PROJECT_DIR/cardinal-opt" --app openmc -i openmc.i --n-threads="$N_THREADS"

test:app_cardinal:openmc_master.i:
  stage: test
  timeout: 30m
  script:
    - env | sort
    - cd problems/spherical_heat_conduction
    - mpirun -np "$N_RANKS" "$CI_PROJECT_DIR/cardinal-opt" --app cardinal -i openmc_master.i --n-threads="$N_THREADS"

test:app_nek:nek.i:
  stage: test
  timeout: 30m
  variables:
    NEKRS_HOME: $CI_PROJECT_DIR/install
  script:
    - env | sort
    - cd problems/spherical_heat_conduction
    - mpirun -np "$N_RANKS" "$CI_PROJECT_DIR/cardinal-opt" --app nek -i nek.i --nekrs-setup onepebble2

test:app_cardinal:nek_master.i:
  stage: test
  timeout: 30m
  variables:
    NEKRS_HOME: $CI_PROJECT_DIR/install
  script:
    - env | sort
    - cd problems/spherical_heat_conduction
    - mpirun -np "$N_RANKS" "$CI_PROJECT_DIR/cardinal-opt" --app cardinal -i nek_master.i --nekrs-setup onepebble2

test:app_cardinal:master.i:
  stage: test
  timeout: 30m
  variables:
    NEKRS_HOME: $CI_PROJECT_DIR/install
  script:
    - env | sort
    - cd problems/spherical_heat_conduction
    - mpirun -np "$N_RANKS" "$CI_PROJECT_DIR/cardinal-opt" --app cardinal -i master.i --nekrs-setup onepebble2 --n-threads="$N_THREADS"


