Content:
    cardinal:
        root_dir: doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - contrib/**
            - css/**
            - js/**
            - media/**

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: Cardinal
        repo: https://github.com/neams-th-coe/cardinal
        menu:
            Getting Started:
                Installing Cardinal: start.md
                How to Contribute: contributing.md
            Documentation:
                Tutorials: tutorials/index.md
                Input File Syntax: source/index.md
                Code-Specific Theory: theory/index.md
                Doxygen: doxygen/html/classes.html
                Running on HPC: hpc.md
            Publications: publications.md
            Contact: contact.md
            Help: faq.md
            News: news.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include
        active: true
    MooseDocs.extensions.acronym:
        acronyms:
            moose: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
            vtb: !include ${ROOT_DIR}/doc/acronyms.yml
